stages:
  download_data:
    cmd: python src/download.py
    deps:
    - params/params.yaml
    - src/download.py
    outs:
    - data/raw
  prepare_data:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - outputs/processed
  process_data:
    cmd: python src/process.py
    deps:
    - data/raw
    - src/process.py
    outs:
    - outputs_process/processed
  evaluate_data:
    cmd: python src/evaluate.py
    deps:
    - outputs/processed
    - outputs_process/processed
    - src/evaluate.py
    outs:
    - results/evaluation_results.txt
